### ISSUE TITLE
Changes on using a 9dof from adafruit

### ISSUE THREAD

**Issue by varnit15112** [TKJElectronics/Example-Sketch-for-IMU-including-Kalman-filter#10]
Hey

I'm trying to detect the pose of an object using the 9dof from adafruit, could you please suggest me the required changes?

Also are the advantages of using a 9dof over a 6dof for pose detection?

Thank you

**Comment by Lauszus** [comment]
Sorry, but this not the place to get coding guidance, you should ask at the Adafruit forum instead: https://forums.adafruit.com/.
