### ISSUE TITLE
use kalman fillter for accelerometer?

### ISSUE THREAD

**Issue by avsingh999** [TKJElectronics/Example-Sketch-for-IMU-including-Kalman-filter#11]
I have doubt In
https://github.com/TKJElectronics/Example-Sketch-for-IMU-including-Kalman-filter/blob/master/IMU/MPU6050/MPU6050.ino
Have you used a kalman filtter for accelerometer??
because I think you have used only kalman for gyrocope not for  accelerometer??

**Comment by Lauszus** [comment]
@avsingh999 the MPU-6050 is a combined 3-axis accelerometer and 3-axis gyroscope.
