### ISSUE TITLE
'TWBR' was not declared in this scope (example MPU6050)

### ISSUE THREAD

**Issue by elingeniero3** [TKJElectronics/Example-Sketch-for-IMU-including-Kalman-filter#15]
Hi mates,

I'm a noob using Arduino.I haveve  connected the pins correctrly and installed the library. I have  tried the example code (MPU6050) but I can't get it to compile, the error that show me is:
'TWBR' was not declared in this scope

![imagen](https://user-images.githubusercontent.com/45800532/103927757-27e1ac00-511b-11eb-86a2-f9e9ae8b835a.png)

And if I declare it the TWBR as a double or other type (or delete it) the program compiles but the serial monitor and the serial ploter appears empty, in blank.

Someone could help me please?

**Comment by Lauszus** [comment]
Replace it with:

```C++
Wire.setClock(400000);
```

**Comment by elingeniero3** [comment]
Many thanks for your help, now compile but i still get an empty serial monitor (and ploter). I don't know what the cause can be. I've check all the Hardware i use an ESP32 and IMU9250( it have the MPU6050 inside). Could you help me please?
![imagen](https://user-images.githubusercontent.com/45800532/104018026-7776b500-51b9-11eb-915b-558a3820122e.png)
