### ISSUE TITLE
wrong data , when mpu accelerated in y or z ditrction

### ISSUE THREAD

**Issue by EmbeddedAndMore** [TKJElectronics/Example-Sketch-for-IMU-including-Kalman-filter#4]
hi
thanks to you for this library
i print complementary and kalman output , and as you mentioned in code the initial roll and pitch come from accelerometer data

  double roll  = atan2(accY, accZ) \* RAD_TO_DEG;
  double pitch = atan(-accX / sqrt(accY \* accY + accZ \* accZ)) \* RAD_TO_DEG;

here is the problem , of course it's final effect in complementary filter is just 7% but when i accelerate my board for example in y direction ,  my roll show 10 deg and as acceleration become more the roll number shows bigger number .
and of course it affects my kalman filter output.
is this  a normal behavior or this is my bad implementation ??

thanks in advance
MA

**Comment by Lauszus** [comment]
So you are not using the Kalman filter I provided?

Yes you need to tune the complimentary. Try to “trust” the gyroscope more. Also read this article I wrote about the Kalman filter: http://blog.tkjelectronics.dk/2012/09/a-practical-approach-to-kalman-filter-and-how-to-implement-it/.
