### ISSUE TITLE
No need to wait after Wire.requestFrom() and no .beginTransmission() or .endTransmission needed.

### ISSUE THREAD

**Issue by Koepel** [TKJElectronics/Example-Sketch-for-IMU-including-Kalman-filter#7]
The Wire.beginTransmission() and Wire.endTransmission() are only used when writing data, they should not be used with Wire.requestFrom().

When the Wire.requestFrom() returns, the I2C transaction has completely finished and the received data is waiting in a buffer in the Wire library. There is no need to wait for something.

In the file "Example-Sketch-for-IMU-including-Kalman-filter/IMU/ITG3205_ADXL345/ITG3205_ADXL345.ino", in the function i2cRead(), the Wire.requestFrom() is encapsulated by Wire.beginTransmission() and Wire.endTransmission. Those Wire.beginTransmission() and Wire.endTransmission() can be removed.

In the files "Example-Sketch-for-IMU-including-Kalman-filter/IMU/MPU6050/I2C.ino" and "Example-Sketch-for-IMU-including-Kalman-filter/IMU/MPU6050_HMC5883L/I2C.ino", in the function "i2cRead()", there is a while-loop with a counter and micros(), but there is nothing to wait for.
If you want, you could check if the number of received bytes is the same as the number of requested bytes.

```
  Wire.requestFrom(IMUAddress, nbytes, (uint8_t)true); // Send a repeated start and then release the bus after reading
  if (Wire.available() != nbytes) {
    return 5; // This error value is not already taken by endTransmission
  }
  for (uint8_t i = 0; i < nbytes; i++) {
    data[i] = Wire.read();
  }
  return 0; // Success
}
```

**Comment by Lauszus** [comment]
Since this does not have real benefits and the code in the library have been proven to work with multiple different kind of microcontrollers, then I see no real benefit by changing it. If you really want to change it, then you can submit a PR and do some testing.
