### ISSUE TITLE
problem with degree at MPU6050_HMC5883L result

### ISSUE THREAD

**Issue by jzishwa** [TKJElectronics/Example-Sketch-for-IMU-including-Kalman-filter#8]
there is a problem with MPU6050_HMC5883L code , where at 90 degree the result just 60 degree. how to fix it? how i calibrate hmc5883l? help me, thank's

**Comment by Lauszus** [comment]
You need to set the minimum and maximum values of the magnetometer here: https://github.com/TKJElectronics/Example-Sketch-for-IMU-including-Kalman-filter/blob/master/IMU/MPU6050_HMC5883L/MPU6050_HMC5883L.ino#L43-L50.
