### ISSUE TITLE
About x,y displacement

### ISSUE THREAD

**Issue by ss87021456** [TKJElectronics/Example-Sketch-for-IMU-including-Kalman-filter#9]
I'd wonder wether this MPU-6050 with kalman filter can be apply on calculating the displacement of x, y?
Since I'm working on a project need to build a system that can calculate the current 2-D displacement with MPU-6050, and then do some application of tracking object.

**Comment by Lauszus** [comment]
Yes that is possible using a Kalman filter. In my experience you do not get very good results over long time if you are using a IMU only, that is why people often use a GPS or similar in combination with it when estimating the position.
